[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "0.11.2"

[[constraint]]
  name = "github.com/stretchr/testify"
  branch = "master"

[[constraint]]
  name = "k8s.io/client-go"
  version = "5.0.1"

[[constraint]]
  name = "github.com/prometheus/client_golang/prometheus/promhttp"
  version = "0.8.0"

[[constraint]]
  name = "github.com/prometheus/client_golang/prometheus"
  version = "0.8.0"
